export type WorkerSecrets = {
  GOOGLE_SERVICE_ACCOUNT_EMAIL: string;
  GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY: string;
  GEMINI_API_KEY: string;
  ADMIN_API_KEY: string;
};

// Env bindings are generated by `wrangler types`; only dashboard-managed secrets are added here.
export type WorkerEnv = Env & WorkerSecrets;
